### ISSUE TITLE
Stayed black first time, now starts but globe isn't there.

### ISSUE THREAD

**Issue by luminaryphi** [Eunanibus/MMM-Globe#5]
Hi,
I tried to install this and the first time I used it Magic Mirror stayed black and my pi froze. I turned it off and back on again, now whenever I start it Magic Mirror will boot up, but the globe module does not appear. I tried changing the sizes and the position but shifting small things like that does not make the globe appear.

**Comment by onkelbobby** [comment]
Hi there,
I installed the module to my Mirror (latest release) but it is also not showing the globe. My Pi did not freeze but still after several changes and reboots no globe appearing.

**Comment by Eunanibus** [comment]
Hi guys. Please visit the [main forum discussion link](https://forum.magicmirror.builders/topic/2553/mmm-globe?page=1) for assistance here. The advice a while back was that unless you are running the module on a non-pi hardware backing the mirror, the process is a little too heavy for Pi's - The globe not appearing is either due to the restraints on processing, or the that the open3GL drivers are not configured correctly.

**Comment by onkelbobby** [comment]
Hi,

 

thank you for this hint... I thought the RPi3 has enough power ...

 

 

Gesendet: Sonntag, 18. Februar 2018 um 11:23 Uhr
Von: Eunan <notifications@github.com>
An: Eunanibus/MMM-Globe <MMM-Globe@noreply.github.com>
Cc: onkelbobby <benjaminbopp@web.de>, Comment <comment@noreply.github.com>
Betreff: Re: [Eunanibus/MMM-Globe] Stayed black first time, now starts but globe isn't there. (#5)


Hi guys. Please visit the [https://forum.magicmirror.builders/topic/2553/mmm-globe?page=1](main forum discussion link) for assistance here. The advice a while back was that unless you are running the module on a non-pi hardware backing the mirror, the process is a little too heavy for Pi's - The globe not appearing is either due to the restraints on processing, or the that the open3GL drivers are not configured correctly.
